spring.application.name=rrss

# SQLite DataSource Configuration
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Disable Thymeleaf cache to fix hot reloading
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/

logging.level.root=ERROR
logging.level.org.thymeleaf.TemplateEngine=OFF

# Email Configuration
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
