spring.application.name=rrss

# SQLite DataSource Configuration
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Disable Thymeleaf cache to fix hot reloading
spring.thymeleaf.cache=false
