driverClassName=org.sqlite.JDBC
url=jdbc:sqlite:data/rrss.db
username=someuser
password=ourSUP3R!secureP@SSW0RD
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=true