driverClassName=org.sqlite.JDBC
db.path=rrss.sqlite
username=someuser
password=ourSUP3R!secureP@SSW0RD
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=true
